apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-knvd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0046-tenant/ci1t-830-0046-app/devfile-sample-knvd@sha256:218202c0a9d2b9b4034f7ba1bb7e61566bb4594faf3f04694c3ebb076801a739
        name: my-nodejs
        resources: {}
status: {}
